### ISSUE TITLE
MemcachedMock#normalizeTime should not use `time()` for zero value

### ISSUE THREAD

**Issue by tmatsuo** [GeckoPackages/GeckoMemcacheMock#5]
[`MemcachedMock#normalize()`]( https://github.com/GeckoPackages/GeckoMemcacheMock/blob/2.0/src/MemcacheMock/MemcachedMock.php#L1267) uses the value from `time()` when the `$expiration` is null or zero, but I think it's a problematic behavior. When the client code uses `Memcached#set()` without `$expiration`, it should be considered without any expiration, but this mock sets the current time as an expiration. This causes flaky test if you `set` and `get` in your test.

**Comment by SpacePossum** [comment]
@tmatsuo thank you for the report. I hope to look into this soon.

**Comment by SpacePossum** [comment]
This should be fixed through https://github.com/GeckoPackages/GeckoMemcacheMock/pull/7, 
released with 1.2 and 2.1.
Please let me know if the there is still an issue.
